name: Deploy Lambda Function

# This workflow will deploy the Lambda function on push to main branch
# Updated to include proper dependency installation
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.txt -t ./package

      - name: Create deployment package
        run: |
          mkdir -p lambda_package
          cp -r src/* lambda_package/
          cp -r package/* lambda_package/
          cd lambda_package
          zip -r ../deployment.zip .
          cd ..

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name portfolio_form \
            --zip-file fileb://deployment.zip